[workspace]
channels = ["conda-forge"]
name = "graph"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.8,<4"
numpy = ">=2.3.5,<3"
pandas = ">=2.3.3,<3"
seaborn = ">=0.13.2,<0.14"
